#include "FizzyEnums.h"

MooseEnum getInventoryMetricsEnum() {
  return MooseEnum(
      "INVENTORY_IRRAD_TIME INVENTORY_COOL_TIME INVENTORY_TOTAL_ACTIVITY "
      "INVENTORY_ALPHA_ACTIVITY INVENTORY_BETA_ACTIVITY "
      "INVENTORY_GAMMA_ACTIVITY INVENTORY_TOTAL_HEAT INVENTORY_ALPHA_HEAT "
      "INVENTORY_BETA_HEAT INVENTORY_GAMMA_HEAT INVENTORY_TOTAL_MASS "
      "INVENTORY_TOTAL_ATOMS INVENTORY_INGESTION INVENTORY_INHALATION "
      "INVENTORY_FLUX_AMP INVENTORY_DOSE_RATE");
}

MooseEnum getNuclideMetricsEnum() {
  return MooseEnum(
      "ATOMS GRAMS ACTIVITY ALPHA_ACTIVITY BETA_ACTIVITY GAMMA_ACTIVITY "
      "TOTAL_HEAT ALPHA_HEAT BETA_HEAT GAMMA_HEAT DOSE");
}
