name: MOOSE Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Install Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
         apptainer-version: 1.3.6

      - name: Restore Apptainer library
        run: |
          apptainer remote add --no-login SylabsCloud cloud.sycloud.io
          apptainer remote use SylabsCloud


      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path:  Fizzy 

      - name: Pull Apptainer image
        run: |
          apptainer pull library://billellis.07/fizzy/fizzy_cont_202112

      - name: Build application
        run: |
          apptainer cache clean --force
          df -h
          apptainer overlay create --size 1024 overlay.img
          apptainer exec \
            --bind ${{ github.workspace }}:/workspace \
            --overlay overlay.img \
            fizzy_cont_202112_latest.sif \
            bash -c "
              . /opt/intel/oneapi/setvars.sh &&
              cd /workspace/Fizzy/unit &&
              make -j$(nproc)
            "

      - name: Run tests
        run: |
          apptainer exec \
            --bind ${{ github.workspace }}:/workspace \
            fizzy_cont_202112_latest.sif \
            bash -c "
              cd /workspace/Fizzy/unit &&
              ./fizzy-unit-opt -j$(nproc)
            "
